spring:
  application:
    name: mall-monitor
  profiles:
    active: dev
  security: # 配置登录用户名和密码
    user:
      name: zrk
      password: Aa65602842
  boot:  # 不显示 admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8101
