server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 使用小写 service-id
      routes: # 配置路由路径
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 1
      port: 63790
      host: 118.31.77.172
      password: xhb2025top # Redis服务器连接密码（默认为空）
      timeout: 300ms # 连接超时时间（毫秒）
knife4j:
  gateway:
    enabled: true
    strategy: discover # 网关文档聚合方式：服务发现（自动聚合）
    discover:
      version: openapi3 # 配置 OpenAPI3 规范
      enabled: true # 配置开启服务发现
      excluded-services: mall-monitor # 排除监控服务
    tags-sorter: order # 配置 tag 排序规则
    operations-sorter: order # 配置 operation 排序规则
secure:
  ignore:
    urls: # 配置白名单路径
      - "/doc.html"
      - "/v3/api-docs/swagger-config"
      - "/*/v3/api-docs/default"
      - "/*/v3/api-docs"
      - "/*/swagger-ui/**"
      - "/favicon.ico"
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000 # 60*60*24*30
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-header: true
  # token前缀
  token-prefix: Bearer
  # 是否打印banner
  is-print: false